[package]
name = "awsave"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
aws-config = "1.8.4"
aws-sdk-s3 = "1.96.0"
chacha20 = "0.9.1"
chrono = "0.4.42"
hex = "0.4.3"
sha2 = "0.10.9"
tokio = { version = "1.47.1", features = ["full"] }
